# Generated by Django 5.0.3 on 2024-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('interio', models.IntegerField(blank=True, verbose_name='inteiro')),
                ('Boolean', models.BooleanField(blank=True, null=True, verbose_name='booelan')),
                ('lista', models.CharField(choices=[('1', 'option 1 '), ('F', 'option 2 ')], verbose_name='escolha')),
                ('escolha_radio', models.IntegerField(null=True, verbose_name='escolha radio')),
            ],
        ),
    ]
