# Generated by Django 5.0.3 on 2024-03-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='lista',
        ),
    ]
