# Generated by Django 5.0.3 on 2024-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_teste_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='escolha_radio',
            field=models.IntegerField(null=True, verbose_name='escolharadio'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='texto',
            field=models.TextField(null=True, verbose_name='texto'),
        ),
    ]
