# Generated by Django 5.0.3 on 2024-04-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_teste_escolha_radio_alter_teste_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='alto completo')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('contato', models.CharField(blank=True, max_length=12, verbose_name='numero')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=4, verbose_name='tipo sanguineo')),
                ('rh', models.CharField(blank=True, max_length=1, verbose_name='RH')),
                ('tipo_rh_corretos', models.BooleanField(blank=True, verbose_name='RH corretos')),
                ('situacao', models.CharField(blank=True, verbose_name='situcao')),
            ],
            options={
                'verbose_name': 'Doador',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='alto completo')),
                ('Data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('Hora', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='volume')),
                ('situacao', models.CharField(blank=True, verbose_name='situcao')),
                ('codigo_doador', models.ForeignKey(db_column='codigo_doador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_do', to='APP.doador')),
            ],
            options={
                'verbose_name': 'Doador',
                'ordering': ['codigo'],
            },
        ),
    ]
