# Generated by Django 5.0.3 on 2024-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_doador_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='lista',
            field=models.CharField(choices=[('1', 'option 1 '), ('F', 'option 2 ')], default=1, verbose_name='escolha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teste',
            name='escolha_radio',
            field=models.CharField(null=True, verbose_name='escolharadio'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
