# Generated by Django 5.0.3 on 2024-04-23 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_teste_lista_alter_teste_escolha_radio_alter_teste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='escolha_radio',
            field=models.CharField(default=1, max_length=30, verbose_name='escolharadio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teste',
            name='interio',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, 'O valor inteiro deve ser maior que 0.'), django.core.validators.MaxValueValidator(1000, 'O valor inteiro não pode exceder 1000.')], verbose_name='inteiro'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='texto',
            field=models.TextField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2, 'O texto deve ter no mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(255, 'O texto deve ter no máximo 255 caracteres.')], verbose_name='texto'),
        ),
    ]
