# Generated by Django 5.0.3 on 2024-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_teste_escolha_radio_alter_teste_interio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Boolean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='booelan'),
        ),
    ]
