# Generated by Django 5.0.6 on 2024-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_teste_escolha_alter_teste_escolha_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='rh',
            field=models.CharField(blank=True, choices=[('+', 'Opção 1'), ('-', 'Opção 2')], max_length=1, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A', 'option 1 '), ('B', 'option 2 '), ('AB', 'option 3 '), ('O', 'option 4 ')], max_length=4, verbose_name='tipo sanguineo'),
        ),
    ]
