# Generated by Django 5.0.6 on 2024-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_doador_rh_alter_doador_tipo_sanguineo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='escolha',
        ),
        migrations.AlterField(
            model_name='doador',
            name='rh',
            field=models.CharField(blank=True, choices=[('+', 'RH +   '), ('-', 'RH -   ')], max_length=1, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A', ' tipo A  '), ('B', 'tipo  B  '), ('AB', 'tibo AB  '), ('O', 'tipo  O  ')], max_length=4, verbose_name='tipo sanguineo'),
        ),
    ]
