# Generated by Django 5.0.6 on 2024-05-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_remove_teste_escolha_alter_doador_rh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['codigo'], 'verbose_name': 'Doador', 'verbose_name_plural': 'Doadores'},
        ),
    ]
